version: '3.8'

services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

  rag-agent:
    build: ./rag-agent
    container_name: rag-agent
    ports:
      - "8082:8000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - ollama
      - qdrant
    restart: unless-stopped

  rag-ingestor:
    build: ./rag-ingestor
    container_name: rag-ingestor
    volumes:
      - ./documents:/app/documents
    depends_on:
      - qdrant
    restart: unless-stopped

  rag-uploader:
    build: ./rag-uploader
    container_name: rag-uploader
    ports:
      - "8081:8080"
    volumes:
      - ./documents:/uploads
    restart: unless-stopped

  rag-ui:
    build: ./rag-ui
    container_name: rag-ui
    ports:
      - "3000:3000"
    environment:
      - RAG_AGENT_URL=http://rag-agent:8000
    depends_on:
      - rag-agent
    restart: unless-stopped

volumes:
  ollama_data:
  qdrant_storage:
